{% set data = load_setup_py_data() %}

package:
  name: esgf-compute-api
  version: {{ data.get('version') }}

source:
  path: .

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - owslib

test:
  requires:
    - mock
    - pytest
    - pytest-cov
    - pytest-mock

  files:
    - cwt/tests

  commands:
    - pytest -vvv --cov=cwt --cov-report=xml:/output/coverage.xml --junit-xml=/output/unittest.xml

about:
  home: https://github.com/ESGF/esgf-compute-api
  summary: End-user API for ESGF compute services
