package:
  name: esgf-compute-api
  version: "2.0.0"

source:
  git_rev: master
  git_url: https://github.com/ESGF/esgf-compute-api.git

requirements:
  build:
    - python
    - requests
    - pyxb

  run:
    - python
    - requests
    - pyxb

about:
  home: https://github.com/ESGF/esgf-compute-api
