{% set data = load_setup_py_data() %}

package:
  name: esgf-compute-api
  version: {{ data.get('version') }}

source:
  path: ../

build:
  number: {{ environ.get('BUILD_NUMBER', 0) }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - owslib=0.17.1

about:
  home: https://github.com/ESGF/esgf-compute-api
  summary: End-user API for ESGF compute services
