package:
  name: esgf-compute-api
  version: {{ environ.get('API_VERSION', 'devel') }}

source:
  git_rev: {{ environ.get('GIT_BRANCH', 'devel') }}
  git_url: https://github.com/ESGF/esgf-compute-api.git

build:
  string: py{{ PY_VER }}_{{ GIT_DESCRIBE_HASH }}_{{ environ.get('BUILD_NUMBER', 0) }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - git

  host:
    - python

  run:
    - python
    - owslib

about:
  home: https://github.com/ESGF/esgf-compute-api
  summary: End-user API for ESGF compute services
