package:
  name: esgf-compute-api
  version: "devel"

build:
  number: 5

source:
  git_rev: devel
  git_url: https://github.com/ESGF/esgf-compute-api.git

requirements:
  build:
    - python
    - requests
    - pyxb

  run:
    - python
    - requests
    - pyxb

about:
  home: https://github.com/ESGF/esgf-compute-api
